# SPDX-FileCopyrightText: 2026 David Laws
# SPDX-License-Identifier: CC0-1.0
#
# REUSE metadata for files that cannot carry an inline SPDX header (JSON, editor config) or that
# are covered by a repo-wide default. Per-file headers remain authoritative.

version = 1

[[annotations]]
path = [
    "CMakePresets.json",
    ".ecrc",
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    "README.md",
    "data/*",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 David Laws"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "2025 dcog989"
SPDX-License-Identifier = "MIT"
